import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { REGISTRY } from "../investigations/registry.ts";
import type { Snapshot } from "../investigations/types.ts";
import { auditArticle } from "./audit.ts";
import { traceClaim } from "./trace.ts";

// Runs the real engine against every seed in the registry and pins the output
// to src/investigations/snapshots.generated.ts. This is what keeps the
// Investigations section honest: the verdicts are produced, never authored.
// A seed that fails to trace is skipped (logged) rather than faked.

const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "investigations",
  "snapshots.generated.ts",
);

function renderFile(snapshots: Record<string, Snapshot>): string {
  const entries = Object.entries(snapshots)
    .map(
      ([slug, snap]) =>
        `  ${JSON.stringify(slug)}: ${JSON.stringify(snap, null, 2).replace(/\n/g, "\n  ")},`,
    )
    .join("\n");

  return (
    "// AUTO-GENERATED by `npm run investigations:build` — do not edit by hand.\n" +
    "// Each entry is real engine output pinned on the date below.\n" +
    'import type { Snapshot } from "./types";\n\n' +
    `export const SNAPSHOTS: Record<string, Snapshot> = {\n${entries}\n};\n`
  );
}

async function build(): Promise<number> {
  const pinnedAt = new Date().toISOString().slice(0, 10);
  const snapshots: Record<string, Snapshot> = {};

  for (const inv of REGISTRY) {
    process.stdout.write(`▸ ${inv.slug} … `);
    try {
      if (inv.seed.kind === "trace") {
        const data = await traceClaim({
          article: inv.seed.article,
          phrase: inv.seed.phrase,
          claimText: inv.seed.claimText,
          lang: inv.seed.lang,
        });
        snapshots[inv.slug] = { pinnedAt, data };
        process.stdout.write(`ok — ${data.verdict.primary}\n`);
      } else {
        const data = await auditArticle({
          article: inv.seed.article,
          lang: inv.seed.lang,
        });
        snapshots[inv.slug] = { pinnedAt, data };
        process.stdout.write(`ok — ${Math.round(data.summary.coverage * 100)}% cited\n`);
      }
    } catch (err) {
      process.stdout.write(`SKIP — ${(err as Error).message}\n`);
    }
  }

  writeFileSync(OUT, renderFile(snapshots));
  process.stdout.write(
    `\nWrote ${Object.keys(snapshots).length}/${REGISTRY.length} snapshots → ${OUT}\n`,
  );
  return 0;
}

build().then((code) => {
  process.exitCode = code;
});
